package ConstructionTender;

public enum Professions {
    CIVIL_ENGINEER,
    ARCHITECT,
    SURVEYOR,
    ECONOMIST,
    TECHNOLOGIST,
    CRANE_OPERATOR,
    MASTER_OF_CONSTRUCTION_AND_INSTALLATION_WORKS,
    CARPENTER,
    ROOFER,
    CONCRETE_WORKER,
    PAINTER_PLASTERER

}
